'''
    Files fully generated by GitHub Copilot (GPT-5.3-Codex).
'''

from __future__ import annotations

import argparse
import platform
import subprocess
import sys
from pathlib import Path


def run(command: list[str]) -> None:
    print(f"[RUN] {' '.join(command)}")
    subprocess.run(command, check=True)


def get_venv_python(venv_dir: Path) -> Path:
    if platform.system().lower().startswith("win"):
        return venv_dir / "Scripts" / "python.exe"
    return venv_dir / "bin" / "python"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Create virtual environment and install project dependencies."
    )
    parser.add_argument("--venv", default=".venv", help="Virtual environment directory")
    parser.add_argument(
        "--python",
        default=sys.executable,
        help="Python executable used to create virtual environment",
    )
    parser.add_argument(
        "--no-venv",
        action="store_true",
        help="Install dependencies in current Python environment",
    )
    args = parser.parse_args()

    project_root = Path(__file__).resolve().parent
    requirements_path = project_root / "requirements.txt"
    if not requirements_path.exists():
        print(f"requirements.txt not found: {requirements_path}")
        return 1

    if args.no_venv:
        python_exe = Path(args.python)
    else:
        venv_dir = project_root / args.venv
        run([args.python, "-m", "venv", str(venv_dir)])
        python_exe = get_venv_python(venv_dir)

    run([str(python_exe), "-m", "pip", "install", "--upgrade", "pip"])
    run([str(python_exe), "-m", "pip", "install", "-r", str(requirements_path)])

    print("\n설치가 완료되었습니다.")
    if args.no_venv:
        print("현재 파이썬 환경에서 바로 실행할 수 있습니다.")
    else:
        if platform.system().lower().startswith("win"):
            print(f"가상환경 활성화: {args.venv}\\Scripts\\Activate.ps1")
        else:
            print(f"가상환경 활성화: source {args.venv}/bin/activate")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
